# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminPage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/index.html")
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//input[@type=\'text\' and @name=\'username\']")))
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Username\")]/input").send_keys("wronguser")
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Password\")]/input").send_keys("wrongpassword")
    self.driver.find_element(By.XPATH, "//input[@value=\'Login\']").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//span[contains(@class, \'errorMessage\')]")))
    elements = self.driver.find_elements(By.XPATH, "//span[contains(@class,\'errorMessage\') and contains(normalize-space(.),\"Invalid username and password\")]")
    assert len(elements) > 0
  
  def test_directoryPage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/directory.html")
    self.driver.find_element(By.ID, "directory-grid").click()
    time.sleep(2)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#directory-data")))
    self.vars["directoryText"] = self.driver.find_element(By.CSS_SELECTOR, "#directory-data").text
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\'directory-data\']//*[contains(normalize-space(.),\"Teton Turf and Tree\")]")))
    elements = self.driver.find_elements(By.XPATH, "//div[@id=\'directory-data\']//*[contains(normalize-space(.),\"Teton Turf and Tree\")]")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "directory-list").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "#directory-data")))
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\'directory-data\']//*[contains(normalize-space(.),\"Teton Turf and Tree\")]")))
    elements = self.driver.find_elements(By.XPATH, "//div[@id=\'directory-data\']//*[contains(normalize-space(.),\"Teton Turf and Tree\")]")
    assert len(elements) > 0
  
  def test_homePage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/index.html")
    self.driver.set_window_size(944, 814)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title>h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title>h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".header-logo img")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a.a-button")
    assert len(elements) > 0
    self.driver.close()
  
  def test_joinPage(self):
    self.driver.get("http://127.0.0.1:5501/teton/1.6/index.html/teton/1.6/join.html")
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//label[contains(normalize-space(.),\"First Name\")]/input")))
    elements = self.driver.find_elements(By.XPATH, "//label[contains(normalize-space(.),\"First Name\")]/input")
    assert len(elements) > 0
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"First Name\")]/input").send_keys("John")
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Last Name\")]/input").send_keys("Doe")
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Business Name\")]/input").send_keys("Teton Turf and Tree")
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Title or Position\")]/input").send_keys("Owner")
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//input[@type=\"submit\" and @value=\"Next Step\"]")))
    self.driver.find_element(By.XPATH, "//input[@type=\"submit\" and @value=\"Next Step\"]").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//label[contains(normalize-space(.),\"Email\")]/input")))
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Email\")]/input").send_keys("john.doe@example.com")
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Cell Phone\")]/input").send_keys("208-458-4000")
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//input[@type=\"submit\" and @value=\"Next Step\"]")))
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//label[contains(normalize-space(.),\"Username\")]/input")))
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Username\")]/input").send_keys("wronguser")
    self.driver.find_element(By.XPATH, "//label[contains(normalize-space(.),\"Password\")]/input").send_keys("wrongpassword")
    self.driver.find_element(By.XPATH, "//input[@value=\'Login\']").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//span[contains(@class, \'errorMessage\')]")))
    elements = self.driver.find_elements(By.XPATH, "//span[contains(@class,\'errorMessage\') and contains(normalize-space(.),\"Invalid username and password\")]")
    assert len(elements) > 0
  
